/********************************************************************************
** Form generated from reading UI file 'modificar_moto.ui'
**
** Created by: Qt User Interface Compiler version 5.3.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MODIFICAR_MOTO_H
#define UI_MODIFICAR_MOTO_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>

QT_BEGIN_NAMESPACE

class Ui_Modificar_moto
{
public:
    QComboBox *cb_modificar_moto;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_6;
    QLabel *label_9;
    QPushButton *pb_agragar_moto_cancelar_modificar;
    QRadioButton *rb_estado_reparado_moto_modificar;
    QLineEdit *le_marca_moto_modificar;
    QRadioButton *rb_carretilla_si_modificar;
    QRadioButton *rb_estado_bueno_moto_modificar;
    QLabel *label_5;
    QLabel *label_8;
    QLabel *label_11;
    QDoubleSpinBox *dsb_moto_gastos_reparacion_modificar;
    QRadioButton *rb_estado_bueno_carretilla_modificar;
    QRadioButton *rb_estado_malo_moto_modificar;
    QLabel *label_10;
    QDoubleSpinBox *dsb_moto_precio_compra_modificar;
    QPushButton *pb_agregar_moto_aceptar_modificar;
    QRadioButton *rb_carretilla_no_modificar;
    QDoubleSpinBox *dsb_moto_gastos_reparacion_carretilla_modificar;
    QDoubleSpinBox *dsb_moto_km_recorridos_modificar;
    QRadioButton *rb_estado_malo_carretilla_modificar;
    QRadioButton *rb_estado_reparado_carretilla_modificar;
    QLabel *label_7;
    QDoubleSpinBox *dsb_moto_precio_compra_carretilla_modificar;
    QLabel *label_4;
    QLineEdit *le_placa_moto_modificar;
    QLabel *lb_error_gastos_sidecar;
    QLabel *lb_error_gastos_moto;
    QLabel *lb_error_estado_sidecar;
    QLabel *lb_error_marca_moto;
    QLabel *lb_error_km_moto;
    QLabel *lb_error_placa_moto;
    QLabel *lb_error_estado_moto;
    QLabel *lb_error_precio_compra_sidecar;
    QLabel *lb_error_sidecar;
    QLabel *lb_error_precio_compra_moto;
    QButtonGroup *buttonGroup;
    QButtonGroup *buttonGroup_2;
    QButtonGroup *buttonGroup_3;

    void setupUi(QDialog *Modificar_moto)
    {
        if (Modificar_moto->objectName().isEmpty())
            Modificar_moto->setObjectName(QStringLiteral("Modificar_moto"));
        Modificar_moto->resize(586, 406);
        cb_modificar_moto = new QComboBox(Modificar_moto);
        cb_modificar_moto->setObjectName(QStringLiteral("cb_modificar_moto"));
        cb_modificar_moto->setGeometry(QRect(360, 70, 151, 27));
        label = new QLabel(Modificar_moto);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(250, 10, 141, 21));
        QFont font;
        font.setPointSize(14);
        label->setFont(font);
        label_2 = new QLabel(Modificar_moto);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(30, 60, 67, 17));
        label_3 = new QLabel(Modificar_moto);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(30, 90, 67, 17));
        label_6 = new QLabel(Modificar_moto);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(40, 320, 131, 16));
        label_9 = new QLabel(Modificar_moto);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(280, 120, 241, 16));
        pb_agragar_moto_cancelar_modificar = new QPushButton(Modificar_moto);
        pb_agragar_moto_cancelar_modificar->setObjectName(QStringLiteral("pb_agragar_moto_cancelar_modificar"));
        pb_agragar_moto_cancelar_modificar->setGeometry(QRect(160, 360, 99, 27));
        pb_agragar_moto_cancelar_modificar->setCursor(QCursor(Qt::PointingHandCursor));
        rb_estado_reparado_moto_modificar = new QRadioButton(Modificar_moto);
        buttonGroup_3 = new QButtonGroup(Modificar_moto);
        buttonGroup_3->setObjectName(QStringLiteral("buttonGroup_3"));
        buttonGroup_3->addButton(rb_estado_reparado_moto_modificar);
        rb_estado_reparado_moto_modificar->setObjectName(QStringLiteral("rb_estado_reparado_moto_modificar"));
        rb_estado_reparado_moto_modificar->setGeometry(QRect(110, 240, 91, 22));
        le_marca_moto_modificar = new QLineEdit(Modificar_moto);
        le_marca_moto_modificar->setObjectName(QStringLiteral("le_marca_moto_modificar"));
        le_marca_moto_modificar->setGeometry(QRect(100, 60, 141, 27));
        rb_carretilla_si_modificar = new QRadioButton(Modificar_moto);
        buttonGroup = new QButtonGroup(Modificar_moto);
        buttonGroup->setObjectName(QStringLiteral("buttonGroup"));
        buttonGroup->addButton(rb_carretilla_si_modificar);
        rb_carretilla_si_modificar->setObjectName(QStringLiteral("rb_carretilla_si_modificar"));
        rb_carretilla_si_modificar->setGeometry(QRect(60, 140, 81, 22));
        rb_estado_bueno_moto_modificar = new QRadioButton(Modificar_moto);
        buttonGroup_3->addButton(rb_estado_bueno_moto_modificar);
        rb_estado_bueno_moto_modificar->setObjectName(QStringLiteral("rb_estado_bueno_moto_modificar"));
        rb_estado_bueno_moto_modificar->setGeometry(QRect(30, 240, 71, 22));
        label_5 = new QLabel(Modificar_moto);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(40, 280, 131, 16));
        label_8 = new QLabel(Modificar_moto);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(310, 240, 131, 16));
        label_11 = new QLabel(Modificar_moto);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(40, 160, 191, 20));
        dsb_moto_gastos_reparacion_modificar = new QDoubleSpinBox(Modificar_moto);
        dsb_moto_gastos_reparacion_modificar->setObjectName(QStringLiteral("dsb_moto_gastos_reparacion_modificar"));
        dsb_moto_gastos_reparacion_modificar->setEnabled(false);
        dsb_moto_gastos_reparacion_modificar->setGeometry(QRect(440, 240, 111, 27));
        dsb_moto_gastos_reparacion_modificar->setMaximum(1e+06);
        rb_estado_bueno_carretilla_modificar = new QRadioButton(Modificar_moto);
        buttonGroup_2 = new QButtonGroup(Modificar_moto);
        buttonGroup_2->setObjectName(QStringLiteral("buttonGroup_2"));
        buttonGroup_2->addButton(rb_estado_bueno_carretilla_modificar);
        rb_estado_bueno_carretilla_modificar->setObjectName(QStringLiteral("rb_estado_bueno_carretilla_modificar"));
        rb_estado_bueno_carretilla_modificar->setEnabled(false);
        rb_estado_bueno_carretilla_modificar->setGeometry(QRect(280, 140, 71, 22));
        rb_estado_malo_moto_modificar = new QRadioButton(Modificar_moto);
        buttonGroup_3->addButton(rb_estado_malo_moto_modificar);
        rb_estado_malo_moto_modificar->setObjectName(QStringLiteral("rb_estado_malo_moto_modificar"));
        rb_estado_malo_moto_modificar->setGeometry(QRect(210, 240, 61, 22));
        label_10 = new QLabel(Modificar_moto);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(250, 170, 191, 20));
        dsb_moto_precio_compra_modificar = new QDoubleSpinBox(Modificar_moto);
        dsb_moto_precio_compra_modificar->setObjectName(QStringLiteral("dsb_moto_precio_compra_modificar"));
        dsb_moto_precio_compra_modificar->setGeometry(QRect(180, 280, 111, 27));
        dsb_moto_precio_compra_modificar->setMaximum(1e+06);
        pb_agregar_moto_aceptar_modificar = new QPushButton(Modificar_moto);
        pb_agregar_moto_aceptar_modificar->setObjectName(QStringLiteral("pb_agregar_moto_aceptar_modificar"));
        pb_agregar_moto_aceptar_modificar->setGeometry(QRect(310, 360, 99, 27));
        pb_agregar_moto_aceptar_modificar->setCursor(QCursor(Qt::PointingHandCursor));
        rb_carretilla_no_modificar = new QRadioButton(Modificar_moto);
        buttonGroup->addButton(rb_carretilla_no_modificar);
        rb_carretilla_no_modificar->setObjectName(QStringLiteral("rb_carretilla_no_modificar"));
        rb_carretilla_no_modificar->setGeometry(QRect(140, 140, 71, 22));
        dsb_moto_gastos_reparacion_carretilla_modificar = new QDoubleSpinBox(Modificar_moto);
        dsb_moto_gastos_reparacion_carretilla_modificar->setObjectName(QStringLiteral("dsb_moto_gastos_reparacion_carretilla_modificar"));
        dsb_moto_gastos_reparacion_carretilla_modificar->setEnabled(false);
        dsb_moto_gastos_reparacion_carretilla_modificar->setGeometry(QRect(450, 170, 111, 27));
        dsb_moto_gastos_reparacion_carretilla_modificar->setMaximum(1e+06);
        dsb_moto_km_recorridos_modificar = new QDoubleSpinBox(Modificar_moto);
        dsb_moto_km_recorridos_modificar->setObjectName(QStringLiteral("dsb_moto_km_recorridos_modificar"));
        dsb_moto_km_recorridos_modificar->setGeometry(QRect(180, 320, 111, 27));
        dsb_moto_km_recorridos_modificar->setMaximum(1e+06);
        rb_estado_malo_carretilla_modificar = new QRadioButton(Modificar_moto);
        buttonGroup_2->addButton(rb_estado_malo_carretilla_modificar);
        rb_estado_malo_carretilla_modificar->setObjectName(QStringLiteral("rb_estado_malo_carretilla_modificar"));
        rb_estado_malo_carretilla_modificar->setEnabled(false);
        rb_estado_malo_carretilla_modificar->setGeometry(QRect(460, 140, 61, 22));
        rb_estado_reparado_carretilla_modificar = new QRadioButton(Modificar_moto);
        buttonGroup_2->addButton(rb_estado_reparado_carretilla_modificar);
        rb_estado_reparado_carretilla_modificar->setObjectName(QStringLiteral("rb_estado_reparado_carretilla_modificar"));
        rb_estado_reparado_carretilla_modificar->setEnabled(false);
        rb_estado_reparado_carretilla_modificar->setGeometry(QRect(360, 140, 91, 22));
        label_7 = new QLabel(Modificar_moto);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(30, 120, 201, 17));
        dsb_moto_precio_compra_carretilla_modificar = new QDoubleSpinBox(Modificar_moto);
        dsb_moto_precio_compra_carretilla_modificar->setObjectName(QStringLiteral("dsb_moto_precio_compra_carretilla_modificar"));
        dsb_moto_precio_compra_carretilla_modificar->setEnabled(false);
        dsb_moto_precio_compra_carretilla_modificar->setGeometry(QRect(70, 180, 111, 27));
        dsb_moto_precio_compra_carretilla_modificar->setMaximum(1e+06);
        label_4 = new QLabel(Modificar_moto);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(30, 220, 131, 16));
        le_placa_moto_modificar = new QLineEdit(Modificar_moto);
        le_placa_moto_modificar->setObjectName(QStringLiteral("le_placa_moto_modificar"));
        le_placa_moto_modificar->setGeometry(QRect(100, 90, 141, 27));
        lb_error_gastos_sidecar = new QLabel(Modificar_moto);
        lb_error_gastos_sidecar->setObjectName(QStringLiteral("lb_error_gastos_sidecar"));
        lb_error_gastos_sidecar->setEnabled(true);
        lb_error_gastos_sidecar->setGeometry(QRect(570, 170, 16, 21));
        QPalette palette;
        QBrush brush(QColor(253, 2, 8, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(211, 211, 211, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(255, 255, 255, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush3(QColor(233, 233, 233, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        QBrush brush4(QColor(105, 105, 105, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
        QBrush brush5(QColor(141, 141, 141, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
        QBrush brush6(QColor(252, 3, 3, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        QBrush brush7(QColor(5, 2, 2, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush7);
        palette.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        QBrush brush8(QColor(0, 0, 0, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush8);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        QBrush brush9(QColor(255, 255, 220, 255));
        brush9.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush9);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush8);
        QBrush brush10(QColor(255, 7, 7, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush10);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush7);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush8);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush9);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush8);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush8);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush9);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush8);
        lb_error_gastos_sidecar->setPalette(palette);
        lb_error_gastos_sidecar->setFont(font);
        lb_error_gastos_moto = new QLabel(Modificar_moto);
        lb_error_gastos_moto->setObjectName(QStringLiteral("lb_error_gastos_moto"));
        lb_error_gastos_moto->setEnabled(true);
        lb_error_gastos_moto->setGeometry(QRect(560, 240, 16, 21));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush7);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush8);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush9);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush10);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush7);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush9);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush8);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush8);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush9);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush8);
        lb_error_gastos_moto->setPalette(palette1);
        lb_error_gastos_moto->setFont(font);
        lb_error_estado_sidecar = new QLabel(Modificar_moto);
        lb_error_estado_sidecar->setObjectName(QStringLiteral("lb_error_estado_sidecar"));
        lb_error_estado_sidecar->setEnabled(true);
        lb_error_estado_sidecar->setGeometry(QRect(530, 140, 16, 21));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush7);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush8);
        palette2.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipBase, brush9);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipText, brush8);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush10);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush7);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush8);
        palette2.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush9);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush9);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush8);
        lb_error_estado_sidecar->setPalette(palette2);
        lb_error_estado_sidecar->setFont(font);
        lb_error_marca_moto = new QLabel(Modificar_moto);
        lb_error_marca_moto->setObjectName(QStringLiteral("lb_error_marca_moto"));
        lb_error_marca_moto->setEnabled(true);
        lb_error_marca_moto->setGeometry(QRect(250, 60, 16, 21));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette3.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette3.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette3.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette3.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush7);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Shadow, brush8);
        palette3.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipBase, brush9);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipText, brush8);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush10);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette3.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush7);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Shadow, brush8);
        palette3.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush9);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush8);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette3.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Shadow, brush8);
        palette3.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush9);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush8);
        lb_error_marca_moto->setPalette(palette3);
        lb_error_marca_moto->setFont(font);
        lb_error_km_moto = new QLabel(Modificar_moto);
        lb_error_km_moto->setObjectName(QStringLiteral("lb_error_km_moto"));
        lb_error_km_moto->setEnabled(true);
        lb_error_km_moto->setGeometry(QRect(300, 320, 16, 21));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette4.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette4.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette4.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette4.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush7);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Shadow, brush8);
        palette4.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipBase, brush9);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipText, brush8);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush10);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette4.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette4.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush7);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Shadow, brush8);
        palette4.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush9);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush8);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette4.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette4.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette4.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Shadow, brush8);
        palette4.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush9);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush8);
        lb_error_km_moto->setPalette(palette4);
        lb_error_km_moto->setFont(font);
        lb_error_placa_moto = new QLabel(Modificar_moto);
        lb_error_placa_moto->setObjectName(QStringLiteral("lb_error_placa_moto"));
        lb_error_placa_moto->setEnabled(true);
        lb_error_placa_moto->setGeometry(QRect(250, 90, 16, 21));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette5.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette5.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette5.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette5.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette5.setBrush(QPalette::Active, QPalette::ButtonText, brush7);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Shadow, brush8);
        palette5.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipBase, brush9);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipText, brush8);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush10);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette5.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette5.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::ButtonText, brush7);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Shadow, brush8);
        palette5.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush9);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush8);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette5.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette5.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette5.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Shadow, brush8);
        palette5.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush9);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush8);
        lb_error_placa_moto->setPalette(palette5);
        lb_error_placa_moto->setFont(font);
        lb_error_estado_moto = new QLabel(Modificar_moto);
        lb_error_estado_moto->setObjectName(QStringLiteral("lb_error_estado_moto"));
        lb_error_estado_moto->setEnabled(true);
        lb_error_estado_moto->setGeometry(QRect(270, 240, 16, 21));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette6.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette6.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette6.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette6.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette6.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette6.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette6.setBrush(QPalette::Active, QPalette::ButtonText, brush7);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette6.setBrush(QPalette::Active, QPalette::Shadow, brush8);
        palette6.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipBase, brush9);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipText, brush8);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush10);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette6.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette6.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::ButtonText, brush7);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::Shadow, brush8);
        palette6.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush9);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush8);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette6.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette6.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette6.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Shadow, brush8);
        palette6.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush9);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush8);
        lb_error_estado_moto->setPalette(palette6);
        lb_error_estado_moto->setFont(font);
        lb_error_precio_compra_sidecar = new QLabel(Modificar_moto);
        lb_error_precio_compra_sidecar->setObjectName(QStringLiteral("lb_error_precio_compra_sidecar"));
        lb_error_precio_compra_sidecar->setEnabled(true);
        lb_error_precio_compra_sidecar->setGeometry(QRect(190, 180, 16, 21));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette7.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette7.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette7.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette7.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette7.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette7.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette7.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette7.setBrush(QPalette::Active, QPalette::ButtonText, brush7);
        palette7.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette7.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette7.setBrush(QPalette::Active, QPalette::Shadow, brush8);
        palette7.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette7.setBrush(QPalette::Active, QPalette::ToolTipBase, brush9);
        palette7.setBrush(QPalette::Active, QPalette::ToolTipText, brush8);
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush10);
        palette7.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette7.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette7.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette7.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette7.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette7.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::ButtonText, brush7);
        palette7.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette7.setBrush(QPalette::Inactive, QPalette::Shadow, brush8);
        palette7.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette7.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush9);
        palette7.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush8);
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette7.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette7.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette7.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette7.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette7.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette7.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::Shadow, brush8);
        palette7.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush9);
        palette7.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush8);
        lb_error_precio_compra_sidecar->setPalette(palette7);
        lb_error_precio_compra_sidecar->setFont(font);
        lb_error_sidecar = new QLabel(Modificar_moto);
        lb_error_sidecar->setObjectName(QStringLiteral("lb_error_sidecar"));
        lb_error_sidecar->setEnabled(true);
        lb_error_sidecar->setGeometry(QRect(200, 140, 16, 21));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette8.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette8.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette8.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette8.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette8.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette8.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette8.setBrush(QPalette::Active, QPalette::ButtonText, brush7);
        palette8.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette8.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette8.setBrush(QPalette::Active, QPalette::Shadow, brush8);
        palette8.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette8.setBrush(QPalette::Active, QPalette::ToolTipBase, brush9);
        palette8.setBrush(QPalette::Active, QPalette::ToolTipText, brush8);
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush10);
        palette8.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette8.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette8.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette8.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette8.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette8.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::ButtonText, brush7);
        palette8.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette8.setBrush(QPalette::Inactive, QPalette::Shadow, brush8);
        palette8.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette8.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush9);
        palette8.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush8);
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette8.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette8.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette8.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette8.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette8.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette8.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette8.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette8.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::Shadow, brush8);
        palette8.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush9);
        palette8.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush8);
        lb_error_sidecar->setPalette(palette8);
        lb_error_sidecar->setFont(font);
        lb_error_precio_compra_moto = new QLabel(Modificar_moto);
        lb_error_precio_compra_moto->setObjectName(QStringLiteral("lb_error_precio_compra_moto"));
        lb_error_precio_compra_moto->setEnabled(true);
        lb_error_precio_compra_moto->setGeometry(QRect(300, 280, 16, 21));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette9.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette9.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette9.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette9.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette9.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette9.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette9.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette9.setBrush(QPalette::Active, QPalette::ButtonText, brush7);
        palette9.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette9.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette9.setBrush(QPalette::Active, QPalette::Shadow, brush8);
        palette9.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette9.setBrush(QPalette::Active, QPalette::ToolTipBase, brush9);
        palette9.setBrush(QPalette::Active, QPalette::ToolTipText, brush8);
        palette9.setBrush(QPalette::Inactive, QPalette::WindowText, brush10);
        palette9.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette9.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette9.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette9.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette9.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette9.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette9.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette9.setBrush(QPalette::Inactive, QPalette::ButtonText, brush7);
        palette9.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette9.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette9.setBrush(QPalette::Inactive, QPalette::Shadow, brush8);
        palette9.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette9.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush9);
        palette9.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush8);
        palette9.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette9.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette9.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette9.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette9.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette9.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette9.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette9.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette9.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::Shadow, brush8);
        palette9.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush9);
        palette9.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush8);
        lb_error_precio_compra_moto->setPalette(palette9);
        lb_error_precio_compra_moto->setFont(font);

        retranslateUi(Modificar_moto);
        QObject::connect(pb_agragar_moto_cancelar_modificar, SIGNAL(clicked()), Modificar_moto, SLOT(close()));

        QMetaObject::connectSlotsByName(Modificar_moto);
    } // setupUi

    void retranslateUi(QDialog *Modificar_moto)
    {
        Modificar_moto->setWindowTitle(QString());
        label->setText(QApplication::translate("Modificar_moto", "Modificar Moto", 0));
        label_2->setText(QApplication::translate("Modificar_moto", "Marca:", 0));
        label_3->setText(QApplication::translate("Modificar_moto", "Placa:", 0));
        label_6->setText(QApplication::translate("Modificar_moto", "Km Recorridos:", 0));
        label_9->setText(QApplication::translate("Modificar_moto", "Estado de la  carretila para pasajero", 0));
        pb_agragar_moto_cancelar_modificar->setText(QApplication::translate("Modificar_moto", "Cancelar", 0));
        rb_estado_reparado_moto_modificar->setText(QApplication::translate("Modificar_moto", "Reparado", 0));
        rb_carretilla_si_modificar->setText(QApplication::translate("Modificar_moto", "Si", 0));
        rb_estado_bueno_moto_modificar->setText(QApplication::translate("Modificar_moto", "Bueno", 0));
        label_5->setText(QApplication::translate("Modificar_moto", "Precio de Compra:", 0));
        label_8->setText(QApplication::translate("Modificar_moto", "Gastos Reparacion", 0));
        label_11->setText(QApplication::translate("Modificar_moto", "Precio Compra carretilla", 0));
        rb_estado_bueno_carretilla_modificar->setText(QApplication::translate("Modificar_moto", "Bueno", 0));
        rb_estado_malo_moto_modificar->setText(QApplication::translate("Modificar_moto", "Malo", 0));
        label_10->setText(QApplication::translate("Modificar_moto", "Gastos Reparacion carretilla", 0));
        pb_agregar_moto_aceptar_modificar->setText(QApplication::translate("Modificar_moto", "Aceptar", 0));
        rb_carretilla_no_modificar->setText(QApplication::translate("Modificar_moto", "No", 0));
        rb_estado_malo_carretilla_modificar->setText(QApplication::translate("Modificar_moto", "Malo", 0));
        rb_estado_reparado_carretilla_modificar->setText(QApplication::translate("Modificar_moto", "Reparado", 0));
        label_7->setText(QApplication::translate("Modificar_moto", "Trae Carretila para pasajero?", 0));
        label_4->setText(QApplication::translate("Modificar_moto", "Estado de l a Moto", 0));
        lb_error_gastos_sidecar->setText(QString());
        lb_error_gastos_moto->setText(QString());
        lb_error_estado_sidecar->setText(QString());
        lb_error_marca_moto->setText(QString());
        lb_error_km_moto->setText(QString());
        lb_error_placa_moto->setText(QString());
        lb_error_estado_moto->setText(QString());
        lb_error_precio_compra_sidecar->setText(QString());
        lb_error_sidecar->setText(QString());
        lb_error_precio_compra_moto->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class Modificar_moto: public Ui_Modificar_moto {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MODIFICAR_MOTO_H
